Repository 2factorauth/2fa.directory, pull requests merged in 2023-05, with the labels that each got.

#51 Switch to fillled icons & update BS Icons
  data/categories.json
  layouts/partials/base.stylesheet.html
Labels: UI change

#52 Update the API page
  content/api.md
Labels: enhancement

#53 Update API doc markdown
  content/api.md
Labels: Code enhancement

#54 Deprecate API v1 & v2
  content/api.md
  layouts/shortcodes/warning.html
Labels: documentation
