Repository 2factorauth/2fa.directory, pull requests merged in 2023-08, with the labels that each got.

#57 Add note about API v1 & v2 being unsupported
  content/api.md
Labels: documentation

#59 Remove redundant return
  scripts/generate_regions.rb
Labels: enhancement

#58 Hardcode result for X (Twitter)
  assets/js/search.js
Labels: enhancement

#55 Generate from local path
  scripts/generate_entries.rb
  scripts/generate_regions.rb
Labels: Code enhancement
