Repository 2factorauth/2fa.directory, pull requests merged in 2024-11, with the labels that each got.

#73 Update search results
  index.html
  src/components/search.js
  src/components/search.jsx
Labels: Code enhancement

#74 Fix build failure
  src/components/search.js
Labels: bug

#76 Hide categories title when searching and undo sorting
  src/components/search.js
Labels: Code enhancement

#77 Redirect with query parameters
  functions/redirect.js
  src/components/search.js
  src/components/table.jsx
Labels: Code enhancement

#78 Fix searching in the international region
  src/components/search.js
Labels: Code enhancement

#80 Remove query parameter if there is no query
  src/components/search.js
Labels: Code enhancement

#81 Update README
  README.md
Labels: documentation

#82 Speed up redirect function
  functions/redirect.js
Labels: Code enhancement

#79 Add error pages
  502.html
  index.html
  src/components/style.directory.js
  src/components/style.error.js
  src/components/style.js
  vite.config.js
Labels: Code enhancement

#86 Replace Bootstrap Icons with Google Material Symbols
  assets/css/category-buttons.scss
  assets/css/navbar.scss
  assets/css/search.scss
  public/_headers
  src/components/category.js
  src/components/head.js
  src/components/regions.js
Labels: Code enhancement

#87 Fix icons in tables
  assets/css/search.scss
  assets/css/table.scss
  public/icons/algolia.svg
  public/icons/facebook.svg
  public/icons/x.svg
  src/components/head.js
  src/components/table.jsx
Labels: Code enhancement

#89 Add info icon back
  assets/css/table.scss
  src/components/head.js
  src/components/table.jsx
Labels: Code enhancement

#88 HTML & CSS updates
  assets/css/page.scss
  assets/css/root.scss
  assets/css/search.scss
  index.html
  src/components/category.js
  src/components/dialog.js
  src/components/table.jsx
Labels: Code enhancement

#90 Fix custom methods component
  src/components/table.jsx
Labels: Code enhancement

#92 Fix social notices
  src/components/table.jsx
Labels: Code enhancement

#94 Add sitemap
  functions/sitemap.xml.js
  public/robots.txt
Labels: Code enhancement

#93 Add service worker
  public/icons/maskable.png
  public/manifest.json
  public/service-worker.js
  src/components/style.js
  src/serviceWorker.js
Labels: Code enhancement

#95 Add apple touch icon
  public/icons/apple-touch-icon.png
  src/components/head.js
Labels: enhancement
